### ISSUE TITLE
Access denied to mariadb (using password: NO)

### ISSUE THREAD

**Issue by mike-trewartha** [bitnami/bitnami-docker-express#110]
When attempting to connect to the mysql db running in the mariadb container, access is denied to 'UNKNOWN_USER'@'localhost'

**Steps to reproduce the issue:**
As per: https://docs.bitnami.com/aws/how-to/ecs-rds-tutorial/

1.
mkdir express-app
cd express-app
curl -L -o docker-compose.yml https://raw.githubusercontent.com/bitnami/bitnami-docker-express/master/docker-compose-mariadb.yml

2. docker-compose up -d

3. docker-compose exec mariadb mysql myapp

**Describe the results you received:**

MacBook-Pro:my-app user$ docker-compose exec mariadb mysql myapp
ERROR 1045 (28000): Access denied for user 'UNKNOWN_USER'@'localhost' (using password: NO)
MacBook-Pro:my-app user$

**Describe the results you expected:**

I expected to connect to the myapp db in MariaDB
mysql>

**Version**

- Output of `docker version`:

```
MacBook-Pro:my-app user$ docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
MacBook-Pro:my-app user$ docker info
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 24PP:EHOK:6KCO:4F66:TOJD:SZWO:ZVRO:ET5R:MXZV:DCJO:MCDG:56KF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 56
 Goroutines: 93
 System Time: 2018-11-26T00:57:34.8231455Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
MacBook-Pro:my-app user$ docker-compose version
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @mike-trewartha, you need to specify a user for the MariaDB client (by default "root" is created):

    docker-compose exec mariadb mysql -u root myapp

**Comment by mike-trewartha** [comment]
thanks marcosbc - hopefully the guide is updated.

**Comment by rafaeleyng** [comment]
I've got here from: https://docs.bitnami.com/aws/how-to/ecs-rds-tutorial/

I suggest you to update that guide, it might be confusing a lot of people who are reading it.

**Comment by marcosbc** [comment]
That's a good point @rafaeleyng! We're working on fixing it.

**Comment by marcosbc** [comment]
Hi! This was fixed, so I'm closing this issue.
