### ISSUE TITLE
Never versions of Node and NPM?

### ISSUE THREAD

**Issue by migmartri** [bitnami/bitnami-docker-express#112]
It seems that this Express distribution relies on node 7 (the current LTS is 10.x) and npm 4.x (the stable already running 6.x)

npm 5.x brought an important feature `package-locks` files so I'd love to have it part of this bundle.

Also, any plans or thoughts on replacing npm for yarn or bundle the latter?

Thanks!

**Comment by juan131** [comment]
I agree @migmartri

We should update both NPM and Node.js. I'll open an internal task to work on that. Thanks for reporting it.

> Also, any plans or thoughts on replacing npm for yarn or bundle the latter?

I think we can bundle both package managers in the Express image. We'll take into consideration once we update Node.js and NPM

**Comment by migmartri** [comment]
Thanks @juan131!

**Comment by carrodher** [comment]
It was done some time ago, please feel free to reopen the issue if needed
