### ISSUE TITLE
Express container will not start

### ISSUE THREAD

**Issue by Jake-Neighbors** [bitnami/bitnami-docker-express#114]
**Description**

Docker container for express will not start.

**Steps to reproduce the issue:**

$ mkdir ~/myapp && cd ~/myapp
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-express/master/docker-compose.yml
$ docker-compose up

**Describe the results you received:**

Express container will not start

**Describe the results you expected:**

express container to be running

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:34 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:11:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 31
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-37-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.35GiB
 Name: Khak1s-Media
 ID: ST4C:RNYH:7TPC:QXG2:CXOS:FWAE:LVYQ:GVOZ:5BJZ:6NTK:SRP4:NTRS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (running on a bare metal host with ubuntu 20,04 installed.):**

**Comment by Jake-Neighbors** [comment]
Digging further.

`express_1  | 
express_1  |   warning: the default view engine will not be jade in future releases
express_1  |   warning: use `--view=jade' or `--help' for additional options
express_1  | 
express_1  | 
express_1  |    create : public/
express_1  | /opt/bitnami/node/lib/node_modules/express/node_modules/mkdirp/index.js:90
express_1  |                     throw err0;
express_1  |                     ^
express_1  | 
express_1  | Error: EACCES: permission denied, mkdir '/app/public'
express_1  |     at Object.mkdirSync (fs.js:757:3)
express_1  |     at Function.sync (/opt/bitnami/node/lib/node_modules/express/node_modules/mkdirp/index.js:71:13)
express_1  |     at mkdir (/opt/bitnami/node/lib/node_modules/express/bin/express-cli.js:498:10)
express_1  |     at createApplication (/opt/bitnami/node/lib/node_modules/express/bin/express-cli.js:184:3)
express_1  |     at /opt/bitnami/node/lib/node_modules/express/bin/express-cli.js:472:7
express_1  |     at /opt/bitnami/node/lib/node_modules/express/bin/express-cli.js:384:5
express_1  |     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
myapp_express_1 exited with code 1
`

**Comment by dani8art** [comment]
Hi @Jake-Neighbors, could you try using this?

```diff
    depends_on:
      - mongodb
+   user:<your_user>:0
```

**Comment by Jake-Neighbors** [comment]
I have attempted the suggested change however this does not look to be correct.

i have true user:<uid>:0.  as well as user:<username>0.

The both have syntax error and will not allow the updates to be applied.

**Comment by dani8art** [comment]
You need to run with your username for the host machine and the group `root`, if for example you user in your host machine is `myuser` you should run it as:

```diff
    depends_on:
      - mongodb
+   user: 'myuser:0'
```
