### ISSUE TITLE
CodeEnvy launch not working

### ISSUE THREAD

**Issue by pointful** [bitnami/bitnami-docker-express#81]
The CodeEnvy launch is failing -- here is the error that it stops on:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
 
The following packages have unmet dependencies:
 openjdk-8-jdk-headless : Depends: openjdk-8-jre-headless (= 8u121-b13-1~bpo8+1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Workspace Agent will be downloaded from Workspace Master
/home/bitnami/che/ws-agent/bin/catalina.sh: 1: exec: /home/bitnami/che/jdk1.8/bin/java: not found

Thoughts?

**Comment by juan131** [comment]
@pointful there was a problem related with how Codenvy installed Java runtime. More information at: https://github.com/eclipse/che/issues/3740

It supposed to be fixed now. Could you please confirm us that you're able to launch the Bitnami Docker Express container in a Codenvy workspace?
